return {
  'mason-org/mason.nvim',
  opts = {},
    ensure_installed = {
        'bash-language-server',
        'django-template-lsp',
        'docker-compose-language-service',
        'dockerfile-language-server',
        'gh-actions-language-server',
        'goimports',
        'gopls',
        'html-lsp',
        'json-lsp',
        'lua-language-server',
        'prettier',
        'pyproject-fmt',
        'ruff',
        'shfmt',
        'stylua',
        'terraform',
        'terraform-ls',
    },
    automatic_installation = true,
}
