name: Dotfiles CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Dotfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint shell scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          find . -name '*.sh' -type f -print0 | xargs -0 shellcheck || true

      - name: Check YAML syntax
        run: |
          sudo apt-get install -y yamllint
          find . -name '*.yml' -o -name '*.yaml' | xargs yamllint || true

  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  nix-build:
    name: Nix Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Nix configuration
        run: nix-build '<nixpkgs>' -A hello || true

  home-manager-check:
    name: Home Manager Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Home Manager
        run: |
          nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
          nix-channel --update

      - name: Check Home Manager configuration
        run: |
          export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}
          echo "Home Manager check would run here"

  validation:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [lint, pre-commit, nix-build, home-manager-check]
    steps:
      - name: All checks passed
        run: echo "All validation checks completed successfully!"
