name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build and apply Home Manager config
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
        run: |
          echo "Checking Nix installation and flake support"
          nix --version
          grep -qxF 'experimental-features = nix-command flakes' ~/.config/nix/nix.conf || \
            echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
          echo "Running flake build (home-manager switch)"
          nix run home-manager -- switch --flake ./home-manager#mynixos --impure -b backup

      - name: Validate dotfile presence
        run: |
          test -f ~/.config/nvim/init.lua || echo "Missing Neovim config"
          test -f ~/.config/aerospace/aerospace.toml || echo "Missing aerospace config"
          test -f ~/.config/wezterm/config.lua || echo "Missing Wezterm config"
          test -f ~/.zshrc || echo "Missing Zsh config"
          test -f ~/.gitconfig || echo "Missing Git config"
          test -f ~/.tmux.conf || echo "Missing Tmux config"

      - name: Show Home Manager generations
        run: home-manager generations || true

  validation:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [pre-commit, setup-and-build]
    steps:
      - name: All checks passed
        run: echo "All validation checks completed successfully!"
