name: Dotfiles CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Dotfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint shell scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          find . -name '*.sh' -type f -print0 | xargs -0 shellcheck || true

      - name: Check YAML syntax
        run: |
          sudo apt-get install -y yamllint
          find . -name '*.yml' -o -name '*.yaml' | xargs yamllint || true

  nix-build:
    name: Nix Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Nix configuration
        run: |
          if [ -f "flake.nix" ]; then
            nix build .#homeConfigurations.$(whoami).activationPackage --show-trace || echo "Nix build attempted"
          else
            echo "No flake.nix found, skipping Nix build"
          fi

  home-manager-check:
    name: Home Manager Configuration Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Home Manager configuration
        run: |
          if [ -f "home.nix" ] || [ -f "flake.nix" ]; then
            nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
            nix-channel --update
            echo "Home Manager configuration found"
          else
            echo "No Home Manager configuration found, skipping"
          fi

  validation:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [lint, nix-build, home-manager-check]
    steps:
      - name: All checks passed
        run: echo "All validation checks completed successfully!"
